# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goke < Formula
  desc "Build automation tool using YAML"
  homepage "https://github.com/parabrola/goke"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/parabrola/goke/releases/download/0.3.0/goke_darwin_amd64.tar.gz"
      sha256 "f0e789f0353c9057bef7d8128f7b5ff69a2fb1250328a1301bcc1e7f77076fb5"

      define_method(:install) do
        bin.install "goke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/parabrola/goke/releases/download/0.3.0/goke_darwin_arm64.tar.gz"
      sha256 "b1033bdb5ef7bbc1bd720064cde0cd23487022ec02699d01b0d999a3675f2b96"

      define_method(:install) do
        bin.install "goke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/parabrola/goke/releases/download/0.3.0/goke_linux_amd64.tar.gz"
      sha256 "9d81c148e787b086742b47c8929bcfffaa6ec94bb3b27113d1d79d678c30d4bd"
      define_method(:install) do
        bin.install "goke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/parabrola/goke/releases/download/0.3.0/goke_linux_arm64.tar.gz"
      sha256 "61c1aa3a1d3b6b661293d8decf9ea740fcea708c3025744fbe16c213315d5350"
      define_method(:install) do
        bin.install "goke"
      end
    end
  end
end
