# This file was generated by GoReleaser. DO NOT EDIT.
cask "goke" do
  name "goke"
  desc "Build automation tool using YAML"
  homepage "https://github.com/parabrola/goke"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goke"

  on_macos do
    on_intel do
      url "https://github.com/parabrola/goke/releases/download/#{version}/goke_darwin_amd64.tar.gz"
      sha256 "6e9597d497a9f33f48a1f0ae0676da7fc9beb539eef79900e1444db3609e8bfc"
    end
    on_arm do
      url "https://github.com/parabrola/goke/releases/download/#{version}/goke_darwin_arm64.tar.gz"
      sha256 "8f4431016c4cb934948d20c2b65f3e9037621643d38e7bdf36bc8d189fbfbf7e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/parabrola/goke/releases/download/#{version}/goke_linux_amd64.tar.gz"
      sha256 "de925de28eb38946c2283945ef0580cc57ed6834498a782714acff7b65ce8704"
    end
    on_arm do
      url "https://github.com/parabrola/goke/releases/download/#{version}/goke_linux_arm64.tar.gz"
      sha256 "78a4c2fd3676cad4a4cbf5d13e95717fd4a4822ad9d3fc76d81a01a8eb3b7e16"
    end
  end

  # No zap stanza required
end
